name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: snok/install-poetry@v1.3.3
      with:
        version: 1.7.1
        virtualenvs-create: false

    - name: Install apache-airflow-granulate-databricks-auto-patch
      working-directory: ./apache-airflow-granulate-databricks-auto-patch
      run: poetry install --with dev

    - name: Install apache-airflow-granulate-databricks
      working-directory: ./apache-airflow-granulate-databricks
      run: poetry install --with dev

    - name: Lint with ruff in apache-airflow-granulate-databricks
      working-directory: ./apache-airflow-granulate-databricks
      run: poetry run ruff .

    - name: Format with ruff in apache-airflow-granulate-databricks
      working-directory: ./apache-airflow-granulate-databricks
      run: poetry run ruff format .

    - name: Mypy check in apache-airflow-granulate-databricks
      working-directory: ./apache-airflow-granulate-databricks
      run: poetry run mypy .
