name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: snok/install-poetry@v1.3.3
      with:
        version: 1.7.1
        virtualenvs-create: false

    - name: Install dependencies with poetry
      run: poetry install --with dev
      with:
        path: apache-airflow-granulate-databricks/

    - name: Lint with ruff
      run: |
        poetry run ruff .

    - name: Format with ruff
      run: |
        poetry run ruff format .

    - name: Mypy check
      run: |
        poetry run mypy .
