name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install linters
      run: |
        pip install poetry && cd apache_airflow_granulate_databricks && poetry install --with dev

    - name: Lint with ruff
      run: |
        poetry run ruff .

    - name: Format with ruff
      run: |
        poetry run ruff format .

    - name: Mypy check
      run: |
        poetry run mypy .
